<?xml version="1.0"?>



<robot name="ur5_gripper" xmlns:xacro="http://wiki.ros.org/xacro">

    <gazebo>

      <plugin name="ros_control" filename="libgazebo_ros_control.so">
        <!--robotNamespace>/</robotNamespace-->
        <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
      </plugin>

    </gazebo>

    <xacro:property name="d1" value="0.089159" />
    <xacro:property name="a2" value="-0.42500" />
    <xacro:property name="a3" value="-0.39225" />
    <xacro:property name="d4" value="0.10915" />
    <xacro:property name="d5" value="0.09465" />
    <xacro:property name="d6" value="0.0823" />

    <xacro:property name="base_mass"     value="4.0" /> 
    <xacro:property name="shoulder_mass" value="3.7000" />
    <xacro:property name="upper_arm_mass" value="8.3930" />
    <xacro:property name="forearm_mass" value="2.2750" />
    <xacro:property name="wrist_1_mass" value="1.2190" />
    <xacro:property name="wrist_2_mass" value="1.2190" />
    <xacro:property name="wrist_3_mass" value="0.1879" />

    <xacro:property name="shoulder_height"  value="0.089159" />

    <xacro:property name="shoulder_offset" value="0.13585" /> 

    <xacro:property name="joint_limited"                 value="true" />
    <xacro:property name="safety_limits"                 value="false" />
    <xacro:property name="safety_pos_margin"             value="0.15" />
    <xacro:property name="safety_k_position"             value="20" />   
    <xacro:property name="shoulder_pan_lower_limit"  value="${-pi}" />
    <xacro:property name="shoulder_pan_upper_limit"  value="${pi}" />

    <xacro:property name="shoulder_lift_lower_limit"  value="${-pi}" />
    <xacro:property name="shoulder_lift_upper_limit"  value="${pi}" />

    <xacro:property name="elbow_offset" value="-0.1197" /> <!-- measured from model -->
    <xacro:property name="upper_arm_length" value="0.42500" />
    <xacro:property name="elbow_joint_lower_limit" value="${-pi}" />
    <xacro:property name="elbow_joint_upper_limit" value="${pi}" />
    
    <xacro:property name="forearm_length" value="${-a3}" />
    <xacro:property name="wrist_1_lower_limit" value="${-pi}" />
    <xacro:property name="wrist_1_upper_limit" value="${pi}" />

    <xacro:property name="wrist_1_length" value="${d4 - elbow_offset - shoulder_offset}" />
    <xacro:property name="wrist_2_lower_limit" value="${-pi}" />
    <xacro:property name="wrist_2_upper_limit" value="${pi}" />

    <xacro:property name="wrist_2_length" value="${d5}" />
    <xacro:property name="wrist_3_lower_limit" value="${-pi}" />
    <xacro:property name="wrist_3_upper_limit" value="${pi}" />

    <xacro:property name="wrist_3_length" value="${d6}" />

    <!-- 惯性矩阵的函数，输入半径和长度即可 -->
    <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
        <inertial>
        <mass value="${mass}" />
        <!-- <xacro:insert_block name="origin" /> -->
        <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
            iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
            izz="${0.5 * mass * radius * radius}" />
        </inertial>
    </xacro:macro>

    <link name="world" />

    <joint name="world_joint" type="fixed">
        <parent link="world" />
        <child link = "base_link" />
        <origin xyz="0.0 0.0 0.75" rpy="0.0 0.0 0.0" />
    </joint>


    <link name="base_link" >   <!-- 机械臂基座 -->

      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/base.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>

      <collision>  <!-- 碰撞检测 -->
        <geometry>       
          <mesh filename="package://ur_gazebo/mesh/collision/base.stl" />
        </geometry>
      </collision>

      <xacro:cylinder_inertial radius="0.06" length="0.05" mass="${base_mass}">  <!-- 惯性矩阵 -->
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
      
    </link> 

    <!-- 机械臂第一个关节自由度 -->
    <joint name="shoulder_pan_joint" type="revolute">

      <parent link="base_link" />
      <child link = "shoulder_link" />

      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />

      <axis xyz="0 0 1" />  <!-- z轴为转动轴 -->

      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>

      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_pan_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_pan_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>

      <dynamics damping="0.0" friction="0.0"/>

    </joint>

    <transmission name="shoulder_pan_trans">

      <type>transmission_interface/SimpleTransmission</type>

      <joint name="shoulder_pan_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>

      <actuator name="shoulder_pan_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>

    </transmission>


    <!-- 第一个连杆 -->
    <link name="shoulder_link">  

      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/shoulder.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/collision/shoulder.stl" />
        </geometry>
      </collision>

      <xacro:cylinder_inertial radius="0.06" length="0.15" mass="${shoulder_mass}" >
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
     
    </link>

    <gazebo reference="shoulder_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    

    <!-- 机械臂第二个关节轴 -->

    <joint name="shoulder_lift_joint" type="revolute">

      <parent link="shoulder_link" />
      <child link = "upper_arm_link" />

      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi/2.0} 0.0" />

      <axis xyz="0 1 0" />

      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>

      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_lift_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_lift_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>

      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <transmission name="shoulder_lift_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="shoulder_lift_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="shoulder_lift_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>


    <!-- 第二个连杆 -->
    <link name="upper_arm_link">

      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/upperarm.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/collision/upperarm.stl" />
        </geometry>
      </collision>

      <xacro:cylinder_inertial radius="0.06" length="0.56" mass="${upper_arm_mass}" >
        <origin xyz="0.0 0.0 0.28" rpy="0 0 0" />
      </xacro:cylinder_inertial>

    </link>

    <gazebo reference="upper_arm_link">
      <selfCollide>true</selfCollide>
    </gazebo>

    <joint name="elbow_joint" type="revolute">

      <parent link="upper_arm_link" />
      <child link = "forearm_link" />

      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />

      <axis xyz="0 1 0" />

      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>

      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${elbow_joint_lower_limit + safety_pos_margin}" soft_upper_limit="${elbow_joint_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>

      <dynamics damping="0.0" friction="0.0"/>

    </joint>

    <transmission name="elbow_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="elbow_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="elbow_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>


    <link name="forearm_link">

      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/forearm.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/collision/forearm.stl" />
        </geometry>
      </collision>

      <xacro:cylinder_inertial radius="0.06" length="${-a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-a3/2}" rpy="0 0 0" />
      </xacro:cylinder_inertial>

    </link>

    <gazebo reference="forearm_link">
      <selfCollide>true</selfCollide>
    </gazebo>

    <joint name="wrist_1_joint" type="revolute">

      <parent link="forearm_link" />
      <child link = "wrist_1_link" />

      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />

      <axis xyz="0 1 0" />

      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="28.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>

      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="28.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_1_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_1_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>

      <dynamics damping="0.0" friction="0.0"/>

    </joint>

    <transmission name="wrist_1_trans">

      <type>transmission_interface/SimpleTransmission</type>

      <joint name="wrist_1_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>

      <actuator name="wrist_1_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <link name="wrist_1_link">

      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/wrist1.dae" />
        </geometry>

        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>

      </visual>

      <collision>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/collision/wrist1.stl" />
        </geometry>
      </collision>

      <xacro:cylinder_inertial radius="0.06" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>

    </link>

    <gazebo reference="wrist_1_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <!-- ******************************************************************************************************** -->


    <joint name="wrist_2_joint" type="revolute">

      <parent link="wrist_1_link" />
      <child link = "wrist_2_link" />

      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />

      <axis xyz="0 0 1" />

      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="28.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>

      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="28.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_2_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_2_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>

      <dynamics damping="0.0" friction="0.0"/>

    </joint>

    <transmission name="wrist_2_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="wrist_2_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="wrist_2_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>


    <link name="wrist_2_link">

      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/wrist2.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/collision/wrist2.stl" />
        </geometry>
      </collision>

      <xacro:cylinder_inertial radius="0.06" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0 0 0" />
      </xacro:cylinder_inertial>

    </link>

    <gazebo reference="wrist_2_link">
      <selfCollide>true</selfCollide>
    </gazebo>

    <joint name="wrist_3_joint" type="revolute">

      <parent link="wrist_2_link" />
      <child link = "wrist_3_link" />

      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />

      <axis xyz="0 1 0" />

      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="28.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>

      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="28.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_3_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_3_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>

      <dynamics damping="0.0" friction="0.0"/>

    </joint>

    <transmission name="wrist_3_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="wrist_3_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="wrist_3_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <link name="wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/visual/wrist3.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_gazebo/mesh/collision/wrist3.stl" />
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.0375" length="0.0345" mass="${wrist_3_mass}">
        <origin xyz="0.0 ${wrist_3_length - 0.0345/2} 0.0" rpy="${pi/2} 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="wrist_3_link">
      <selfCollide>true</selfCollide>
    </gazebo>


<!--**********************test link****************************-->

    <!-- <joint name="test_to_wrist3" type="fixed">
      <parent link="wrist_3_link" />
      <child link = "test_link" />
      <origin xyz="0.0 0.0 0.0" rpy="0  0  0" />
    </joint>

    <link name="test_link">
      <visual>
        <geometry>
          <box size="0.5 0.3 0.7" />
        </geometry>

        <origin xyz="0 0 0" rpy="0 0 0" />

        <material name="black">
                <color rgba="0.7 0.5 0 0.5" />
        </material>
      </visual>

    </link> -->





<!--===================Camera Base=============================-->
    <!-- <link name="camera_base">
      <collision>
        <geometry>
          <box size="0.02 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.01 0 0"/>
        <material name="black">
            <color rgba="0.7 0.5 0 0.5" />
        </material>
      </collision>
    </link>

    <joint name="wrist_3_link-camera_base" type="fixed">
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <parent link="wrist_3_link"/>
      <child link="camera_base"/>
    </joint> -->
<!--============================================================-->

    <joint name="wrist_3_link-tool0_fixed_joint" type="fixed">

      <origin xyz="0 ${wrist_3_length} 0" rpy="${-pi/2} 0 0"/>

      <parent link="wrist_3_link"/>
      <child link="tool0"/>

    </joint>

    <link name="tool0"/>

<!--************************************************************-->

    <joint name="gripper_base_joint" type="fixed">
            <parent link="tool0"/>
            <child link="gripper_base_link"/>
            <origin xyz="0 0 0" rpy="0 ${-pi/2} 0"/>
            <!-- <xacro:insert_block name="origin"/> -->

    </joint>
        
    <link name="gripper_base_link">

        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_base_link.dae"/>
            </geometry>

        </visual>

        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_base_link.stl"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.636951" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000380" ixy = "0.000000" ixz = "0.000000"
                      iyx = "0.000000" iyy = "0.001110" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.001171" />
        </inertial>

    </link>

    <gazebo reference="gripper_base_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo> 

    <joint name="gripper_finger1_joint" type="revolute">
        <parent link="gripper_base_link"/>
        <child link="gripper_finger1_knuckle_link"/>
        <axis xyz="0 0 1"/>
        <origin rpy="${pi} 0.0 0.0" xyz="0.05490451627 0.03060114443 0.0"/>
        <limit lower="0.0" upper="0.804" velocity="2.0" effort="1000"/>
    </joint>

    <joint name="gripper_finger2_joint" type="revolute">
        <parent link="gripper_base_link"/>
        <child link="gripper_finger2_knuckle_link"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0.0 0.0 0.0" xyz="0.05490451627 -0.03060114443 0.0"/>
        <limit lower="-3.14" upper="3.14" velocity="100.0" effort="1000"/>
        <mimic joint="gripper_finger1_joint"/>
    </joint>

    <!--============================================================================-->

    <link name="gripper_finger1_knuckle_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_knuckle_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_knuckle_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.018491" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000009" ixy = "-0.000001" ixz = "0.000000"
                      iyx = "-0.000001" iyy = "0.000001" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000010" />
        </inertial>
    </link>
        
    <gazebo reference="gripper_finger1_knuckle_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo>   

    <link name="gripper_finger2_knuckle_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_knuckle_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_knuckle_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.018491" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000009" ixy = "-0.000001" ixz = "0.000000"
                      iyx = "-0.000001" iyy = "0.000001" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000010" />
        </inertial>
    </link>

    <gazebo reference="gripper_finger2_knuckle_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo> 

    <joint name="gripper_finger1_finger_joint" type="fixed">
        <parent link="gripper_finger1_knuckle_link"/>
        <child link="gripper_finger1_finger_link"/>
        <origin xyz="-0.00408552455 -0.03148604435 0.0" rpy="0 0 0" />
    </joint>

    <joint name="gripper_finger2_finger_joint" type="fixed">
        <parent link="gripper_finger2_knuckle_link"/>
        <child link="gripper_finger2_finger_link"/>
        <origin xyz="-0.00408552455 -0.03148604435 0.0" rpy="0 0 0" />
    </joint>

    <link name="gripper_finger1_finger_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_finger_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_finger_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.027309" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000003" ixy = "-0.000002" ixz = "0.000000"
                      iyx = "-0.000002" iyy = "0.000021" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000020" />
        </inertial>
    </link>

    <gazebo reference="gripper_finger1_finger_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo>  

    <link name="gripper_finger2_finger_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_finger_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_finger_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.027309" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000003" ixy = "-0.000002" ixz = "0.000000"
                      iyx = "-0.000002" iyy = "0.000021" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000020" />
        </inertial>
    </link>

    <gazebo reference="gripper_finger2_finger_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo>  

    <joint name="gripper_finger1_inner_knuckle_joint" type="continuous">
        <parent link="gripper_base_link"/>
        <child link="gripper_finger1_inner_knuckle_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.06142 0.0127 0" rpy="${pi} 0.0 0.0" />
        <limit lower="-3.14" upper="3.14" velocity="100.0" effort="0.1"/>
        <mimic joint="gripper_finger1_joint" offset="0"/>
    </joint>

    <joint name="gripper_finger2_inner_knuckle_joint" type="continuous">
        <parent link="gripper_base_link"/>
        <child link="gripper_finger2_inner_knuckle_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.06142 -0.0127 0" rpy="0 0 0"/>
        <limit lower="-3.14" upper="3.14" velocity="100.0" effort="0.1"/>
        <mimic joint="gripper_finger1_joint" offset="0"/>
    </joint>

    <link name="gripper_finger1_inner_knuckle_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_inner_knuckle_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_inner_knuckle_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.029951" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000039" ixy = "0.000000" ixz = "0.000000"
                      iyx = "0.000000" iyy = "0.000005" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000035" />
        </inertial>
    </link>

    <gazebo reference="gripper_finger1_inner_knuckle_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo> 
    
    <link name="gripper_finger2_inner_knuckle_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_inner_knuckle_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_inner_knuckle_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.029951" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000039" ixy = "0.000000" ixz = "0.000000"
                      iyx = "0.000000" iyy = "0.000005" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000035" />
        </inertial>
    </link>

    <gazebo reference="gripper_finger2_inner_knuckle_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo> 

    <joint name="gripper_finger1_finger_tip_joint" type="continuous">
        <parent link="gripper_finger1_inner_knuckle_link"/>
        <child link="gripper_finger1_finger_tip_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.04303959807 -0.03759940821 0.0" rpy="0.0 0.0 0.0"/>
        <limit lower="-3.14" upper="3.14" velocity="100.0" effort="0.1"/>
        <mimic joint="gripper_finger1_joint" multiplier="-1"/>
    </joint>

    <joint name="gripper_finger2_finger_tip_joint" type="continuous">
        <parent link="gripper_finger2_inner_knuckle_link"/>
        <child link="gripper_finger2_finger_tip_link"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0.0 0.0 0.0" xyz="0.04303959807 -0.03759940821  0.0"/>
        <limit lower="-3.14" upper="3.14" velocity="100.0" effort="0.1"/>
        <mimic joint="gripper_finger1_joint" multiplier="-1"/>
    </joint>


    <link name="gripper_finger1_finger_tip_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_finger_tip_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_finger_tip_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.019555" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000002" ixy = "0.000000" ixz = "0.000000"
                      iyx = "0.000000" iyy = "0.000005" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000006" />
        </inertial>
    </link> 
    
    <gazebo reference="gripper_finger1_finger_tip_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo> 

    <link name="gripper_finger2_finger_tip_link">
        <visual>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/visual/robotiq_85_finger_tip_link.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://ur_gazebo/mesh/collision/robotiq_85_finger_tip_link.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.019555" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx = "0.000002" ixy = "0.000000" ixz = "0.000000"
                      iyx = "0.000000" iyy = "0.000005" iyz = "0.000000"
                      izx = "0.000000" izy = "0.000000" izz = "0.000006" />
        </inertial>
    </link>
    
    <gazebo reference="gripper_finger2_finger_tip_link">
        <implicitSpringDamper>1</implicitSpringDamper>
        <mu1>100000</mu1>
        <mu2>100000</mu2>
        <kp>100000000.0</kp>
        <kd>1.0</kd>
    </gazebo> 


    <transmission name="gripper_finger1_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="gripper_finger1_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="gripper_finger1_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <gazebo>
            <!-- loading plugin: mimic joints works in gazebo now -->
        <plugin filename="libroboticsgroup_gazebo_mimic_joint_plugin.so" name="mimic_robotiq_85_1">
            <joint>gripper_finger1_joint</joint>
            <mimicJoint>gripper_finger2_joint</mimicJoint>
            <!--multiplier>1.0</multiplier>
            <offset>0.0</offset-->
        </plugin>
        <plugin filename="libroboticsgroup_gazebo_mimic_joint_plugin.so" name="mimic_robotiq_85_2">
            <joint>gripper_finger1_joint</joint>
            <mimicJoint>gripper_finger2_inner_knuckle_joint</mimicJoint>
            <!--multiplier>1.0</multiplier>
            <offset>0.0</offset-->
        </plugin>
        <plugin filename="libroboticsgroup_gazebo_mimic_joint_plugin.so" name="mimic_robotiq_85_3">
            <joint>gripper_finger1_joint</joint>
            <mimicJoint>gripper_finger1_inner_knuckle_joint</mimicJoint>
            <!--multiplier>1.0</multiplier>
            <offset>0.0</offset-->
        </plugin>
        <plugin filename="libroboticsgroup_gazebo_mimic_joint_plugin.so" name="mimic_robotiq_85_4">
            <joint>gripper_finger1_joint</joint>
            <mimicJoint>gripper_finger1_finger_tip_joint</mimicJoint>
            <multiplier>-1.0</multiplier>
            <offset>0.0</offset>
        </plugin>
        <plugin filename="libroboticsgroup_gazebo_mimic_joint_plugin.so" name="mimic_robotiq_85_5">
            <joint>gripper_finger1_joint</joint>
            <mimicJoint>gripper_finger2_finger_tip_joint</mimicJoint>
            <multiplier>-1.0</multiplier>
            <offset>0.0</offset>
        </plugin>
    </gazebo>

<!--=====================Gripper_TCP==================================================-->
    <joint name="wrist_3_link-tool0_fixed_joint" type="fixed">

      <origin xyz="0 ${wrist_3_length} 0" rpy="${-pi/2} 0 0"/>

      <parent link="wrist_3_link"/>
      <child link="tool0"/>

    </joint>

    <link name="Gripper_TCP"/>

        
<!--=====================Camera=============================================================-->

    <joint name="camera_base_joint" type="fixed">
      <parent link="wrist_3_link" />
      <child link = "camera_base_link" />
      <!--origin xyz="0.0 ${wrist_3_length+0.155} 0.0" rpy="0.0 0.0 ${pi/2.0}" /-->
      <origin xyz="0.11 ${wrist_3_length/2+0.017} 0.0" rpy="0  0  0" />
    </joint>

    <link name="camera_base_link"/>

    <xacro:include filename="$(find realsense_ros_gazebo)/xacro/depthcam.xacro"/>
    <xacro:realsense_d435 sensor_name="d435" parent_link="camera_base_link" rate="10">
      <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0"/>
    </xacro:realsense_d435>

</robot>